// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAH_zFZTMGltw_pDdxSk7k1kIWyQO9fF4Q',
    appId: '1:461541333578:web:a1eadc042ff36a65d3a4b3',
    messagingSenderId: '461541333578',
    projectId: 'notesapp-a5358',
    authDomain: 'notesapp-a5358.firebaseapp.com',
    storageBucket: 'notesapp-a5358.appspot.com',
    measurementId: 'G-4332V5FKEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6r3oGkLR_bp0qqh-oIeuRBv6BTd8-744',
    appId: '1:461541333578:android:0b297736fd597b59d3a4b3',
    messagingSenderId: '461541333578',
    projectId: 'notesapp-a5358',
    storageBucket: 'notesapp-a5358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUzsSp4Zt3fup1xa0znfV4tkKAzngW5Ek',
    appId: '1:461541333578:ios:bb98a53c4a993d78d3a4b3',
    messagingSenderId: '461541333578',
    projectId: 'notesapp-a5358',
    storageBucket: 'notesapp-a5358.appspot.com',
    iosBundleId: 'com.example.notesapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUzsSp4Zt3fup1xa0znfV4tkKAzngW5Ek',
    appId: '1:461541333578:ios:fceea1b1539a23eed3a4b3',
    messagingSenderId: '461541333578',
    projectId: 'notesapp-a5358',
    storageBucket: 'notesapp-a5358.appspot.com',
    iosBundleId: 'com.example.notesapp.RunnerTests',
  );
}
